"""Added submission_data to Submission model

Revision ID: 19df40774adb
Revises: db0a187dada6
Create Date: 2025-03-17 02:58:47.682320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19df40774adb'
down_revision = 'db0a187dada6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('submission_data')

    # ### end Alembic commands ###
