"""Add Rubric and RubricCriteria models

Revision ID: 2c833f490de3
Revises: 4fea3e046222
Create Date: 2025-02-13 01:14:52.477556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c833f490de3'
down_revision = '4fea3e046222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubric', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubric', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
