"""Add student_email to Submission model

Revision ID: 6cfb4e7b501c
Revises: 2c833f490de3
Create Date: 2025-03-11 21:25:36.841386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cfb4e7b501c'
down_revision = '2c833f490de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_email', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('student_email')

    # ### end Alembic commands ###
